name: Compilar APK

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Descargar código fuente
        uses: actions/checkout@v4

      - name: Configurar Java (JDK 17)
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Dar permisos de ejecución a Gradlew
        run: chmod +x gradlew

      - name: Compilar APK Debug
        run: ./gradlew assembleDebug --no-daemon

      - name: Subir APK como Artifact
        uses: actions/upload-artifact@v4
        with:
          name: CajaDiaria-debug-apk
          path: app/build/outputs/apk/debug/*.apk
          if-no-files-found: error
